name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Tous les jours Ã  minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: YoannS01
          width: 600
          height: 100
          square: 10
          colors: "ebedf0,9be9a8,40c463,30a14e,216e39"

      - name: Commit Snake
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update snake"
          git push
